name: Deploy Frontend (POC)

on:
  push:
    branches:
      - POC

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Frontend to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd Hackathon_Project_Enigma_FE
            git checkout POC
            git pull origin POC

            docker stop enigma-frontend || true
            docker rm enigma-frontend || true

            docker build -t enigma-frontend .
            docker run -d \
              --name enigma-frontend \
              -p 3000:3000 \
              -e NEXT_PUBLIC_API_BASE_URL=http://15.206.213.150:8000 \
              enigma-frontend
